### ISSUE TITLE
control counter styling issues

### ISSUE THREAD

**Issue by SArpnt** [SthephanShinkufag/bytebeat-composer#5]
text is off-center, and what seems like an attempt to fix it doesn't work properly
```css
#control-counter {
	font-size: 1em;
	line-height: 1.6em;
	cursor: pointer;
}
```
font-size: 1em doesn't make sense, em is already a measure of font size, it just sets the font size to itself.
line height makes the text closer to center but isn't right and changes depending on the font
this styling should fix it:
```css
#control-counter {
	align-self: center;
	cursor: pointer;
}
```
